name: Test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.abc.outputs.test }}
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |

          echo "test=hello" >> "$GITHUB_OUTPUT"
          for changed_file in ${{ steps.abc.outputs.modified }}; do
            if [ ${changed_file} == src/mk_elib/__about__.py ]; then
              
            fi
          done        
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
            
        #if: ${{ needs.job1.outputs.output1 == true }}
        run: echo $OUTPUT1$
        
