name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "Modified:"

          for changed_file in ${{ steps.abc.outputs.modified }}; do
            echo ${changed_file}
            if [ ${changed_file} == src/mk_elib/__about__.py ]; then
              echo "found"
            fi
          done
  print:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: test
        run: |
          echo ${{ steps.abc.outputs.versionChanged }}
