name: Test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "test=found" >> "$GITHUB_OUTPUT$"    
          for changed_file in ${{ steps.abc.outputs.modified }}; do
            echo ${changed_file}
            if [ ${changed_file} == src/mk_elib/__about__.py ]; then
              echo "found"
            fi
          done
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo $OUTPUT1$
