name: Test

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
      - id: step1
        run: echo "test=true" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.output1 == 'false' }}
    steps:
      - uses: actions/checkout@v2.1.0
      - id: something
        run: echo "${{needs.job1.outputs.output1}}"
