# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:        
  release:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Set Git Config
       run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
     - name: Push master to prod
       run: |
        git checkout main
        git pull
        git checkout -B prod
        git merge --no-ff main -m "auto push"
