name: Test2

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MadsKrist/filter-python-version@v1
      - id: step1
        run: echo "hello"
